# Generated by Django 3.2.8 on 2021-11-27 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flying_from', models.CharField(max_length=225, null=True)),
                ('postcode', models.CharField(max_length=50, null=True)),
                ('no_of_bags', models.CharField(max_length=25, null=True)),
                ('updated_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
