# Generated by Django 3.2.8 on 2021-12-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0002_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(blank=True, max_length=25, null=True),
        ),
    ]
