# Generated by Django 3.2.8 on 2021-12-14 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0003_alter_customer_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('email', models.EmailField(max_length=225)),
            ],
        ),
    ]
