# Generated by Django 3.2.7 on 2022-01-13 05:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0004_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='FormField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tripe_type', models.CharField(max_length=200)),
                ('laguage_type', models.CharField(max_length=200)),
                ('From', models.CharField(max_length=200)),
                ('To', models.CharField(max_length=200)),
                ('arrival', models.CharField(max_length=200)),
                ('Return', models.CharField(max_length=200)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='luggage.customer')),
            ],
        ),
    ]
