# Generated by Django 3.2.7 on 2022-01-13 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0005_auto_20220113_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='luggage.customer'),
        ),
    ]
