# Generated by Django 3.2.7 on 2022-01-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luggage', '0006_alter_formfield_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='Return',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='formfield',
            name='arrival',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
